### ISSUE TITLE
Unable to build with 'npm run build-debug' in step 8.1.1

### ISSUE THREAD

**Issue by Mackiovello** [rustwasm/wasm_game_of_life#29] opened 2018-07-23 10:21 UTC
Reproduction:

```
$ rustup update
info: syncing channel updates for 'stable-x86_64-unknown-linux-gnu'
info: syncing channel updates for 'nightly-x86_64-unknown-linux-gnu'
info: checking for self-updates

   stable-x86_64-unknown-linux-gnu unchanged - rustc 1.27.2 (58cc626de 2018-07-18)
  nightly-x86_64-unknown-linux-gnu unchanged - rustc 1.29.0-nightly (874dec25e 2018-07-21)

$ rustup install nightly
info: syncing channel updates for 'nightly-x86_64-unknown-linux-gnu'

  nightly-x86_64-unknown-linux-gnu unchanged - rustc 1.29.0-nightly (874dec25e 2018-07-21)

$ rustup target add wasm32-unknown-unknown --toolchain nightly
info: component 'rust-std' for target 'wasm32-unknown-unknown' is up to date
$ node -v
v8.11.3
$ npm -v
5.6.0
$ cargo +nightly install wasm-bindgen-cli
    Updating registry `https://github.com/rust-lang/crates.io-index`
  Installing wasm-bindgen-cli v0.2.13
error: binary `wasm-bindgen` already exists in destination as part of `wasm-bindgen-cli v0.2.12`
binary `wasm2es6js` already exists in destination as part of `wasm-bindgen-cli v0.2.12`
Add --force to overwrite
$ git clone https://github.com/rustwasm/wasm_game_of_life.git
Cloning into 'wasm_game_of_life'...
remote: Counting objects: 324, done.
remote: Compressing objects: 100% (21/21), done.
remote: Total 324 (delta 8), reused 18 (delta 3), pack-reused 295
Receiving objects: 100% (324/324), 593.38 KiB | 747.00 KiB/s, done.
Resolving deltas: 100% (162/162), done.
Checking connectivity... done.
$ cd ./wasm_game_of_life
$ git checkout -b chapter-zero origin/chapter-zero
Branch chapter-zero set up to track remote branch chapter-zero from origin.
Switched to a new branch 'chapter-zero'
$ npm install
npm WARN wasm_game_of_life No description
npm WARN wasm_game_of_life No repository field.
npm WARN wasm_game_of_life No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 598 packages in 10.811s
$ npm run build-debug

> @ build-debug /home/erlend/rust/rust-fun/tutorials/wasm_game_of_life
> cargo +nightly build --target wasm32-unknown-unknown && wasm-bindgen target/wasm32-unknown-unknown/debug/wasm_game_of_life.wasm --out-dir .

   Compiling unicode-xid v0.1.0
   Compiling wasm-bindgen-shared v0.2.11
   Compiling itoa v0.4.1
   Compiling dtoa v0.4.2
   Compiling serde v1.0.55
   Compiling proc-macro2 v0.3.8
   Compiling proc-macro2 v0.4.8
error[E0599]: no method named `to_string` found for type `std::path::PathBuf` in the current scope
   --> /home/erlend/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro2-0.4.8/src/unstable.rs:290:52
    |
290 |         let filename = stable::file_name(sf.path().to_string());
    |                                                    ^^^^^^^^^
    |
    = note: the method `to_string` exists but the following trait bounds were not satisfied:
            `std::path::PathBuf : std::string::ToString`
            `std::path::Path : std::string::ToString`
    = help: did you mean `to_str`?

error: aborting due to previous error

For more information about this error, try `rustc --explain E0599`.
error: Could not compile `proc-macro2`.
warning: build failed, waiting for other jobs to finish...
error: build failed
npm ERR! code ELIFECYCLE
npm ERR! errno 101
npm ERR! @ build-debug: `cargo +nightly build --target wasm32-unknown-unknown && wasm-bindgen target/wasm32-unknown-unknown/debug/wasm_game_of_life.wasm --out-dir .`
npm ERR! Exit status 101
npm ERR!
npm ERR! Failed at the @ build-debug script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/erlend/.npm/_logs/2018-07-23T10_16_24_669Z-debug.log
$ cat  /home/erlend/.npm/_logs/2018-07-23T10_16_24_669Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'build-debug' ]
2 info using npm@5.6.0
3 info using node@v8.11.3
4 verbose run-script [ 'prebuild-debug', 'build-debug', 'postbuild-debug' ]
5 info lifecycle @~prebuild-debug: @
6 info lifecycle @~build-debug: @
7 verbose lifecycle @~build-debug: unsafe-perm in lifecycle true
8 verbose lifecycle @~build-debug: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/erlend/rust/rust-fun/tutorials/wasm_game_of_life/node_modules/.bin:/home/erlend/.cargo/bin:/home/erlend/bin:/home/erlend/.local/bin:/home/erlend/.cargo/bin:/home/erlend/bin:/home/erlend/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/erlend/.dotnet/tools:/home/erlend/.dotnet/tools
9 verbose lifecycle @~build-debug: CWD: /home/erlend/rust/rust-fun/tutorials/wasm_game_of_life
10 silly lifecycle @~build-debug: Args: [ '-c',
10 silly lifecycle   'cargo +nightly build --target wasm32-unknown-unknown && wasm-bindgen target/wasm32-unknown-unknown/debug/wasm_game_of_life.wasm --out-dir .' ]
11 silly lifecycle @~build-debug: Returned: code: 101  signal: null
12 info lifecycle @~build-debug: Failed to exec build-debug script
13 verbose stack Error: @ build-debug: `cargo +nightly build --target wasm32-unknown-unknown && wasm-bindgen target/wasm32-unknown-unknown/debug/wasm_game_of_life.wasm --out-dir .`
13 verbose stack Exit status 101
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid @
15 verbose cwd /home/erlend/rust/rust-fun/tutorials/wasm_game_of_life
16 verbose Linux 4.15.0-24-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "build-debug"
18 verbose node v8.11.3
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 101
22 error @ build-debug: `cargo +nightly build --target wasm32-unknown-unknown && wasm-bindgen target/wasm32-unknown-unknown/debug/wasm_game_of_life.wasm --out-dir .`
22 error Exit status 101
23 error Failed at the @ build-debug script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 101, true ]
```

I tried to follow the steps exactly in https://rustwasm.github.io/book/game-of-life/setup.html. Am I doing something wrong or is there a regression?

**Comment by fitzgen** [comment] 2018-07-24 19:50
This was a regression due to interactions between wasm-bindgen and new nightly rust as we stabilizie more and more of the wasm stuff in nightly rust.

It should be fixed now that we merged #24 which bumped the wasm-bindgen dependency. Thanks for filing an issue!

**Closed by fitzgen** 2018-07-24 19:50 UTC
